name=KeyboardES_ES_Beetle
version=1.0.0
author=Adineamtu
maintainer=Adineamtu
sentence=Spanish (ES-ES) keyboard library for ATmega32U4 (Beetle)
paragraph=Provides correct AltGr, SHIFT and symbol mapping for Spanish keyboard layout on Windows.
category=Device Control
url=https://github.com/Adineamtu/KeyboardES_ES_Beetle_ATmega32u4
architectures=*
